### ISSUE TITLE
Missing images in Safari (desktop & iOS)

### ISSUE THREAD

**Issue by tmns** [zumerlab/snapdom#129]
Hello, I'm considering moving to this library from `modern-screenshot` due to its speed (big props for that, btw!); however, during testing I've noticed that images aren't being included in the generated output on Safari desktop, nor on both Safari and Chrome iOS (my understanding is all browsers on iOS are basically wrappers around Safari anyway). On Chrome and FireFox desktop there's no problem.

The DOM images are a mix of svgs and a webp; though, I've also tried with a png instead of a webp and the result was the same. The webp image is a bit large, but I've also tried with a much smaller sized image and the result was the same again.

Sometimes, it seems that if I try generating a second time, the svgs will show up, but the background image (webp / png) still won't show up. I've also tried `preCache`, and it doesn't seem like it makes a difference. Looks a bit similar to these issues: https://github.com/zumerlab/snapdom/issues/107 & https://github.com/zumerlab/snapdom/issues/73.

This is an example of the expected vs generated images:
<details>
<summary>Expected vs. Generated</summary>
<span>Expected</span><br>
<img width="600" height="1400" alt="Image" src="https://github.com/user-attachments/assets/6e3f0eb1-ebef-420d-b5d6-f739445dd3d1" />
<br><br><span>Generated</span><br>
<img width="600" height="1400" alt="Image" src="https://github.com/user-attachments/assets/2789719a-817a-40b1-a9fc-4394f22adf84" />
</details>

And here is a StackBlitz with my best effort at creating a reproduction: https://stackblitz.com/edit/stackblitz-starters-qq8dqznv?file=app%2Fpage.tsx. In Safari it should output something similar to the "generated" example included above, while in other browsers it should output what's expected.

Also note, the actual code is doing the generation a bit different (using `toBlob` instead of `download`), but the result is the same.

Thanks and let me know if I can provide any other details that would help!

**Comment by tinchox5** [comment]
Thank you @tmns, please let me some time to focus on this issue I thought was fixed. I will use your demo!

**Comment by tinchox5** [comment]
@tmns 

```js
 await snapdom.download(ref.current, {
      format: 'png',
      width: 580 * 2,
      height: 350 * 2,
      embedFonts: true,
      useProxy: 'https://corsproxy.io/?url=',
    });
```

Just in Safari it is needed a `proxy`. I put one as a reference, you can select other. I think that is because of stackBlitz


I left the demo here  https://stackblitz.com/edit/stackblitz-starters-xiecksse?file=app%2Fsnapdom-test.mjs

**Comment by tmns** [comment]
Hey @tinchox5, thanks for addressing this so quickly! Unfortunately, `useProxy` doesn't seem to solve it either, at least not consistently. I tried ten times and the images showed up only once. Below is a video demonstrating with your StackBlitz:

<details>
<summary>🎥</summary>
<video src="https://github.com/user-attachments/assets/dba511bd-a11a-4505-b06b-9cc192a3d667" />
</details>

Also, I don't think it's an issue with StackBlitz specifically, as I originally noticed it while working on my actual app locally. I only used StackBlitz for providing the reproduction.

**Comment by tinchox5** [comment]
Sorry to hear that, but no problem I will continue digging on this issue in some days. 

I realized that the problem is that Safari has a kind of lazy decoding. For instance, I you append the capture as toImg, the outcome image will show the gray background at first and then your image. So, when you exported as png the image is never rendered. I tried different approachs but none worked with consistency. 

In the meantime, you may try by using a smaller background image size and another format like png. Safari converts webp as png. Last thing could help is to reduce the output image size in snapDOM options.

**Comment by tmns** [comment]
> I realized that the problem is that Safari has a kind of lazy decoding. For instance, I you append the capture as toImg, the outcome image will show the gray background at first and then your image. So, when you exported as png the image is never rendered.

Ah that makes sense. The lack of consistency between browsers is ridiculous.

> In the meantime, you may try by using a smaller background image size and another format like png. Safari converts webp as png. Last thing could help is to reduce the output image size in snapDOM options.

Yeah I had tried using a smaller bg image size, png, and smaller output dimensions, but still no luck. Sometimes it would end up correct, but most of the time it would be incorrect.

But anyway, no worries, thanks for the effort! Safari is so annoying 💀

**Comment by tinchox5** [comment]
I'm taking some days off but this issue is important and it is related with custom fonts on Safari and I commited to solve them. 

Last thing, as you have tried other alternatives, did you try to put your image as background-image in the parent div?

**Comment by tmns** [comment]
> Last thing, as you have tried other alternatives, did you try to put your image as background-image in the parent div?

That I actually hadn't tried. Just gave it a go though and still no difference 😮‍💨

> I'm taking some days off but this issue is important and it is related with custom fonts on Safari and I commited to solve them.

Sure thing, enjoy your time off!

**Comment by tinchox5** [comment]
Last thing, you can create a multilayered background-image, mixing a color gradient, logo and support images. That is handled by snapdom

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders/Using_multiple_backgrounds

**Comment by tinchox5** [comment]
I think it is fixed. Always working at https://stackblitz.com/edit/stackblitz-starters-xiecksse?file=app%2Fpage.tsx

**Comment by tinchox5** [comment]
Mmm I tried in a new session and fails first two times

**Comment by tmns** [comment]
Just tried and it failed the first four times, worked the fifth time, then stopped working again for subsequent attempts. 

Sometimes I even get the background, but with the foreground images missing:

<details>
<summary>Ex.</summary>
<img width="600" height="700" alt="Image" src="https://github.com/user-attachments/assets/5df46e14-db0e-4e96-9322-c2bb23ce54c6" />
</details>

Also, seeing the following behavior in Chrome now:
* Load page and download -> image is generated successfully.
* Leave the page for a while (several minutes), come back and download again, I get output like this:

<details>
<summary>Ex.</summary>
<img width="600" height="700" alt="Image" src="https://github.com/user-attachments/assets/2700f576-edd5-4132-8fb3-4b937afc2c17" />
</details>

Tried the above flow on my original StackBlitz and I couldn't reproduce it, so it _may_ be a regression. Not sure though because it's a bit hard to test.

**Comment by tinchox5** [comment]
Yep the version in the demo is a testing lab 😅

**Comment by tinchox5** [comment]
The thing you said about the result after several minutes is related with some caches that may be not properly cleaned

**Comment by tinchox5** [comment]
@tmns, here's the latest version that works for me — hopefully it works for you too.
This version **is super SLOW, inefficient and includes several development logs**, but if it works on your end, it will give me a solid direction to move forward with a cleaner and more efficient solution.

https://stackblitz.com/edit/stackblitz-starters-xiecksse?file=app%2Fpage.tsx

**Comment by tmns** [comment]
@tinchox5 the behavior I'm seeing when opening the app in a fresh session:
* Fails the first time
* Succeeds on most subsequent attempts

For example, last round of testing attempts went like: 1 -> fail, 2-> success, 3 -> success, 4 -> success, 5 -> success, 6 -> fail

With it succeeding more consistently than failing now though, definitely seems like an improvement and things are heading in the right direction!

Also that label lol 🥲

**Comment by tinchox5** [comment]
Check now pls, I disable the use of snapDOM cache.image, I ran all again from scratch and I'm getting 100% success rate.

**Comment by tinchox5** [comment]
StackBlizt webcontainers are beta en Safari, so I run a preview in a separate window

**Comment by tmns** [comment]
Ahh yep, it's working consistently for me now if I run the preview in a separate tab 🙌

**Comment by tinchox5** [comment]
Awesome!!!!

**Comment by tinchox5** [comment]
@tmns after optimizations now appears to be **working super fast and consistently** in the same demo. If ok I will add the solution in next release. I think the same logic could be applied to custom fonts & again.. Safari

**Comment by hawx1993** [comment]
your demo failed on my mac , here is the download result: 

<img width="920" height="593" alt="Image" src="https://github.com/user-attachments/assets/4bc706a2-a0eb-44ec-a9f6-cd62b3304268" />

mac safari Version 18.0.1 (20619.1.26.31.7)

**Comment by tinchox5** [comment]
But if you see this background is working. If you see a gray one it is failing

**Comment by tmns** [comment]
Hmm on the StackBlitz, in a separate tab, it was consistently failing the first time, then succeeding on subsequent attempts.

I was wondering if it was still being affected by StackBlitz somehow, so I took the StackBlitz `snapdom-test.mjs` and used it locally. 

Unfortunately it never works locally, background is always missing. I tried setting the image as a `backgroundImage` on the container `div` as well, but same result.

Then I tried using a relatively small PNG, ~50kb, and it worked consistently in that case! Tried with a ~300kb PNG though and it failed the majority of tries.

**Comment by tinchox5** [comment]
Please try all again fresh start. One hour ago I "touch" a thing. But then I reverted. All my tests worked. Anyway I will create a vanilla demo to test it. Can I use your background image?

**Comment by tmns** [comment]
>  Can I use your background image?

Sure!

**Comment by tinchox5** [comment]
Great! The fix living un your demo is working. It does two things when Safari is detected: 1. Append the image to body to force Sarafi decode it, 2. Waits 300ms before rasterize it. 

Regarding the last point the idea is to make it pro by chequing the url lenght of the original image before rasterize

**Comment by tinchox5** [comment]
Ok I believe the issue was fixed.  This is the modified function:

```js
async function toCanvas(url, { dpr = 1, scale = 1 } = {}) {
  const img = new Image();
  img.src = url;
  img.crossOrigin = 'anonymous';
  img.loading = 'eager';
  img.decoding = 'sync';

  const isSafariBrowser = isSafari();
  let appended = false;

  if (isSafariBrowser) {
    document.body.appendChild(img);
    appended = true;
  }

  await img.decode();

  if (isSafariBrowser) {
    await new Promise(resolve => setTimeout(resolve, 100));
  }

  if (img.width === 0 || img.height === 0) {
    if (appended) img.remove();
    throw new Error('Image failed to load or has no dimensions');
  }

  const width = img.width * scale;
  const height = img.height * scale;

  const canvas = document.createElement('canvas');
  canvas.width = Math.ceil(width * dpr);
  canvas.height = Math.ceil(height * dpr);
  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;

  const ctx = canvas.getContext('2d');
  ctx.scale(dpr, dpr);
  ctx.drawImage(img, 0, 0, width, height);

  if (appended) img.remove();

  return canvas;
}
```


I know this issue affects other similar tools (https://github.com/bubkoo/html-to-image/issues/488), so if interested, the key points are:

- In Safari, calling img.decode() right after setting the source is not always reliable for data URLs or CORS-loaded images.
- Forcing the image into the DOM with document.body.appendChild(img) helps trigger the decoding/rendering pipeline earlier.
- Adding a short setTimeout (e.g., 100ms) after img.decode() appears to give Safari enough time to stabilize the image dimensions before drawing to canvas.
- Always check img.width and img.height after decoding to ensure the image has been properly loaded before drawing.
- Remove the image from the DOM afterward to avoid polluting the document.

This workaround has proven to be the most stable across repeated captures, especially for the first render in Safari.


I left a zip folder with a working demo. [demo.zip](https://github.com/user-attachments/files/21434637/demo.zip)

**Comment by tmns** [comment]
Nice, thanks for the details and all the effort on this. Just a heads up though, I tried dropping `snapdom-test.mjs` into my local app and the bg image is still not showing up in the output 😔 All the other images are showing up consistently though.

FWIW, [modern-snapshot](https://github.com/qq15725/modern-screenshot) seems to get it right somehow (but it's not as fast). Might be worth seeing if what they're doing could be useful here.

**Comment by tinchox5** [comment]
Please increase delay here:

if (isSafariBrowser) {
    await new Promise(resolve => setTimeout(resolve, 100));
  }

my attached demo is downloading  your bg with an output size of 19mb using just a delay of 100ms, but maybe your own environment needs more delay

**Comment by tmns** [comment]
Alright did some testing, looks like it needs `600` on my end.

**Comment by tinchox5** [comment]
In your demo Safari complains about a web font that is set to be preloaded but not used. This may be interfering. Also may try again in your prod mode.

**Comment by titoBouzout** [comment]
@tinchox5  Maybe you can attach an `onload` handler on the `img` instead of using a timeout, and also the order of properties in some browsers matter, I suggest giving the URL last
```js
  img.crossOrigin = 'anonymous';
  img.loading = 'eager';
  img.decoding = 'sync';
  img.src = url;
```
instead of 
```js
  img.src = url;
  img.crossOrigin = 'anonymous';
  img.loading = 'eager';
  img.decoding = 'sync';
```

**Comment by tinchox5** [comment]
Yeap, I agree with you with the order you propose. About onload handler I think the problem is after that, with decoding. But please try it and if you feel that works better u are welcome to create a PR

**Comment by ngoctuan001** [comment]
Hi, can i check if this issue is being resolved yet? Currently when we try, there are still some scenarios that the .toCanvas return blank on Safari. And usually when trigger the second time it will work, but it always fails on first time.

https://github.com/bubkoo/html-to-image/issues/488

html-to-image has the same issue, and one guys mentioning a fix such as recursively calling the capture until the output dataUrl length doesnt change anymore. Can we consider internally implementing this approach instead of relying on the 100ms because different input may need different timing ? Thanks

cc @tinchox5

**Comment by tinchox5** [comment]
Hi, yes I tried this approach but is it not completely reliable. I thought that on V1.9.9 it was solved. Please confirm me that you are using this version. However there was a related issue regarding first capture on custom font that I fixed (but not published yet) that generates a "warmup" of fonts before capturing that works perfectly. So, I could replicate this logic

**Comment by ngoctuan001** [comment]
Yes i was using 1.9.9 . It was hard to replicate the issue with a simple demo. For simple picture it will work. So i actually also not sure what is the core reason, but i will try to explain my scenario (sorry cannot share code)

When i use in my project, my scenario is user can upload the image from local, then they can crop the image on website. Then we use snapdom to capture the final image as dataURI and render as user avatar by feeding to a div with backgroundImg: url(dataURI). For our scenario, the first upload always return blank when doing the capture, but the second upload will work.

What we have tried:  When doing debugging, we found out that after the first upload, dataUrl in toCanvas return blank. But second time onwards, it will have data (even when uploading different image). So user always have issue with first time uploading.

If we manually recursively calling the toCanvas until when dataUrl length doesnt change, then it will work.

**Comment by tinchox5** [comment]
I understand you cannot share your project. Maybe you can create a dummy demo using codesandbox and send it to my profile email. 
Another approach could be to share the snapdom setup you are using.
If not possible you may try to be sure that user image is in your target element for example by forcing a layout or using requestanimationframe. Then run the capture.

Last thing, you may clone the repo, check out dev branch and run npm run compile. Thats because dev version may resolve the issue

**Comment by xylplm** [comment]
我最终没能解决这个问题，这个跨域问题还需要代理服务来解决。实际上对于提升的效率大打折扣。最终我又换回了html2canvas 。期待后续作者能解决这个问题？或许在dom中加载后，将它转换为base64？

**Comment by tinchox5** [comment]
Hi, please read #202 and if you can try the latest dev version. If issue
remains I would need some demo to reproduce and solve the problem
