### ISSUE TITLE
Safari browser cannot load background images when downloading with snapdom

### ISSUE THREAD

**Issue by czero1995** [zumerlab/snapdom#237]
## Environment
- **snapdom version**: 1.9.11 (latest)
- **Browser**: Safari
- **Issue**: Background images fail to load during download operations

## Problem Description
When using snapdom to download content that includes `backgroundImage` CSS properties, the background images fail to load in Safari browser. This appears to be related to Safari's cross-origin restrictions.

hou to resolve?

**Comment by tinchox5** [comment]
I think is fixed on dev version: @zumer/snapdom@1.9.12-dev.0

**Comment by czero1995** [comment]
@tinchox5 I found that it was not a version problem. I upgraded to the specified version but the problem still could not be solved. After my test, it was a problem with the image size. If the image is larger than 100k, it will not be loaded correctly into the background image for the first time on Safari, but it will load normally later.

**Comment by czero1995** [comment]
It failed to load the first time, but it worked fine afterwards. It's obviously not a cross-domain problem.

**Comment by tinchox5** [comment]
Thank you. Yes on second try It usually works. But on the dwv version I worked hard on a solution. Can you create a demo with a heavey image to allow me to refine the solution?

**Comment by tinchox5** [comment]
I went back to latest dev version and I performed some demo test on Safari (mac and ios). From my side 100% of captures of problematic Safari resources such as images, web fonts or masks working perfect at first captures.
